project:
  type: website

website:
  title: "Alphavantage Dashboard"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/theAfricanQuant
        target: _blank
      - icon: twitter
        href: https://twitter.com/theAfricanQuant
        target: _blank
      - href: Alphavantage_Dashboard.qmd
        text: Alphavantage Dashboard
format:
  html:
    theme: [cosmo, custom.scss]
    



