---
title: "Donchian Channel Breakout Dashboard"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: true
format: 
  html: 
    css: custom.scss
---

The dashboard can be found <a href="https://www.sisengai.com/Alphavantage_Dashboard/Alphavantage_Dashboard.html" target="_blank">here</a>!

**The Donchian Channel: A Historical Overview and Mechanism**

The Donchian Channel, developed by Richard Donchian in the mid-20th century, is a technical analysis tool used in financial markets. Donchian, often considered the father of trend following, was a pioneer in systematic trading. The Donchian Channel is constructed by plotting the highest high and the lowest low over a specific period, typically 20 days, creating a visual "channel" on price charts. The concept behind the channel is simple yet powerful: when the price breaks above the upper band, it signals a potential buying opportunity, while a break below the lower band may indicate a selling opportunity.

This method laid the groundwork for trend-following systems, focusing on capturing significant market moves by entering trades when prices break out of predefined ranges. Donchian's work, which emphasized discipline and a rules-based approach, influenced generations of traders and the evolution of systematic trading strategies.

**The Turtle Traders: Founding and Methodology**

In the early 1980s, Richard Dennis, a successful commodities trader, and his partner William Eckhardt conducted an experiment to settle a debate on whether great traders were born or made. They recruited a group of individuals with diverse backgrounds, trained them in a systematic trading strategy, and called them the "Turtle Traders." Dennis and Eckhardt's experiment was rooted in Donchian's principles, particularly the use of breakout strategies.

The Turtles were taught to trade based on variations of the Donchian Channel breakout. Specifically, they used a system where they would enter positions when prices broke above or below a channel defined by the highest high or lowest low of the past 20 or 55 days. This method aligned with Donchian's emphasis on trend-following, aiming to capture large market movements while minimizing the impact of short-term noise.

The Turtle Traders' success demonstrated the effectiveness of systematic trading and the possibility of training individuals to become successful traders. Their experience popularized trend-following strategies and cemented the legacy of Donchian's work in the annals of trading history.